### PR TITLE
Gen 7 support

### LINKED ISSUE #12: Add gen 7 support
* New pokemon
* New abilities
* New moves
* New markings
* New languages
* Hyper training bits

### PR DESCRIPTION
**Pull request by AlMcKinlay**
Initial gen 7 support. Do not merge yet. Not done.

Fixes #12 

TODO:
- [x] Remove _rawPk6 from gen 6
- [x] Add new languages
- [x] Add new markings
- [x] Add hyper training bits
- [x] Add gen number
- [x] New digit on TID?
- [x] Merge in #15 

Tests to add:
- [x]  A gen 1-6 pokemon with gen 6 moves and abilities, nothing special (but nothing gen 7 specific)
- [x] A gen 1-6 pokemon with a gen 7 move or ability
- [x] A gen 7 pokemon with at least 1 new move
- [x] Any pokemon with some blue and some pink markings set
- [x] A pokemon you know the TID of (to check 6 digit TID)
- [x] A pokemon with some hyper training

**Don't squash merge this, so we see @SnowPhoenix 's commit seperately**

### CODE REVIEW

**Comment by not-an-aardvark** [comment]
As discussed in IRC, the plan is:

* Deprecate TID and SID in both gens, but keep them in the object. Compute them the same way in both gens.
* Add `fullTid` (name up for debate) to both gens, representing the 32-bit integer containing both the TID and SID
* Add `idNum` to both gens, representing the number that the game displays (a 5-digit integer equal to TID in gen 6, and a 6-digit integer in gen 7)

**Comment by AlMcKinlay** [comment]
Alright, the tid/sid/tidFull/idNo should be working. I have also put in the code for gen <7 pokemon in gen 7, but no test as I don't want to test with a non-real pk7 for that and we can't get it till bank in Jan.

So, think we just need the new data now.

**Comment by Raia** [comment]
@SnowPhoenix, can you make a PR to merge the other branch into this one? Even if it's not 100% done yet, it'd be good to be able to update the list so that we can get things moving again.

**Comment by AlMcKinlay** [comment]
I think once #15 is merged in, this is good to go. We have preliminary support. There are a few things missing, but not very much. Mostly bank stuff. I think we should at the very least get this merged in and we can add stuff later.

**Comment by Raia** [comment]
Figure it doesn't hurt to say this again so we don't miss it - no squash merge on this one please 🙌

**Comment by AlMcKinlay** [comment]
Ok, fixed a few other things today, and I have manually tested with porybox. I can't see anything obviously wrong. @not-an-aardvark could you give the go-ahead for these to be merged. If we come across issues after that, we can always fix them. But it's easier to fix a few issues with a new PR after we've done the rest of the porybox work than to keep this PR open until we are 100% done.

**Review by not-an-aardvark — APPROVED** [review]
LGTM

**Comment by AlMcKinlay** [comment]
Alrighty. Merging time!

**Pull request merged**
